Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using JDPesca.Models;
using JDPesca.Data;
using JDPesca.Authorization;
using Microsoft.AspNetCore.Authorization;

namespace JDPesca.Controllers
{
    public class ContactController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<ApplicationUser> _userManager;

        public ContactController(
        ApplicationDbContext context,
        IAuthorizationService authorizationService,
        UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _authorizationService = authorizationService;
        }

        // GET: Contact
        public async Task<IActionResult> Index()
        {

            var contacts =  from c in _context.Contact
                            select c;

            var userID = _userManager.GetUserId(User);

            contacts = contacts.Where(contact => contact.OwnerID == userID);

            return View(await contacts.ToListAsync());
        }


        // GET: Contact
        public async Task<IActionResult> ContactList()
        {

            var contacts = from u in _context.Users                                           
                           select u;
            

             //contacts =  from user in _context.Users
                //         join contact in _context.Contact on user.Id equals contact.OwnerID
                //         select new Contact { Name = contact.Name, Address = contact.Address, 
                //                                     City = contact.City, State = contact.State, 
                //                                        Zip = contact.Zip, Email = contact.Email, 
                //OwnerID = user.UserName, ContactId = contact.ContactId}; //produces flat sequence




            return View(await contacts.ToListAsync());
        }


        // GET: Contact/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contact == null)
            {
                return NotFound();
            }

            return View(contact);
        }

        // GET: Contact/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Contact/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ContactEditViewModel editModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editModel);
            }

            var contact = ViewModel_to_model(new Contact(), editModel);

            contact.OwnerID = _userManager.GetUserId(User);

            var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                        User, contact,
                                                        ContactOperations.Create);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            _context.Add(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: Contact/Edit/5
        public async Task<IActionResult> Edit(int? id, string fullList)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.SingleOrDefaultAsync(
                                                        m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(
                                                        User, contact,
                                                        ContactOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            var editModel = Model_to_viewModel(contact);

            return View(editModel);
        }

        // POST: Contact/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ContactEditViewModel editModel)
        {
            if (!ModelState.IsValid)
            {
                return View(editModel);
            }

            // Fetch Contact from DB to get OwnerID.
            var contact = await _context.Contact.SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact,
                                                                ContactOperations.Update);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            contact = ViewModel_to_model(contact, editModel);

            _context.Update(contact);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contact = await _context.Contact.SingleOrDefaultAsync(m => m.ContactId == id);
            if (contact == null)
            {
                return NotFound();
            }

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact,
                                        ContactOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            return View(contact);
        }


        // POST: Contact/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contact = await _context.Contact.SingleOrDefaultAsync(m => m.ContactId == id);

            var isAuthorized = await _authorizationService.AuthorizeAsync(User, contact,
                                        ContactOperations.Delete);
            if (!isAuthorized.Succeeded)
            {
                return new ChallengeResult();
            }

            _context.Contact.Remove(contact);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private bool ContactExists(int id)
        {
            return _context.Contact.Any(e => e.ContactId == id);
        }
    
        private Contact ViewModel_to_model(Contact contact, ContactEditViewModel editModel)
        {
            contact.Address = editModel.Address;
            contact.City = editModel.City;
            contact.Email = editModel.Email;
            contact.Name = editModel.Name;
            contact.State = editModel.State;
            contact.Zip = editModel.Zip;

            return contact;
        }

        private ContactEditViewModel Model_to_viewModel(Contact contact)
        {
            var editModel = new ContactEditViewModel();

            editModel.ContactId = contact.ContactId;
            editModel.Address = contact.Address;
            editModel.City = contact.City;
            editModel.Email = contact.Email;
            editModel.Name = contact.Name;
            editModel.State = contact.State;
            editModel.Zip = contact.Zip;

            return editModel;
        }
    
    }
}

Controllers/OrdersController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using JDPesca.Models;
using JDPesca.Data;
using JDPesca.Authorization;
using Microsoft.AspNetCore.Authorization;
using JDPesca.Services;
using SendGrid.Helpers.Mail;


namespace JDPesca.Controllers
{
    [Authorize(Roles = "Administrator, User")]
    public class OrdersController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly IAuthorizationService _authorizationService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IEmailSender _emailSender;


        public OrdersController(
ApplicationDbContext context,
IAuthorizationService authorizationService,
IEmailSender emailSender,
UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
            _authorizationService = authorizationService;
            _emailSender = emailSender;
        }


        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {

            IList<Models.OrdersViewModels.IndexViewModel> IOrder = new List<Models.OrdersViewModels.IndexViewModel>();
  

            var user = await _userManager.GetUserAsync(User);

            var Rol = await _userManager.GetRolesAsync(user);

            var Ordenes = from c in _context.Orders
                          select c;

            if(Rol.FirstOrDefault() == "User"){

                   Ordenes = from c in _context.Orders
                              where c.UserId == user.Id
                              select c;
   }

           
            var OrderList = await Ordenes.ToListAsync();

            foreach(Orders order in OrderList){

                var Orderuser = await _userManager.FindByIdAsync(order.UserId.ToString());

                IOrder.Add(new Models.OrdersViewModels.IndexViewModel{Orders = order,
                
                    User = Orderuser.UserName
                
                });

            }

            return View(IOrder);

        }

        // GET: /<controller>/Details
        public async Task<IActionResult> Details(int? id)
        {

            IList<Products> ProdList = new List<Products>();

            var vm = new JDPesca.Models.OrdersViewModels.OrderDetailViewModel();



       
            var AllOrder = from o in _context.Orders
                        select o;

            var Order = AllOrder.Where(s => s.OrdersID == id).FirstOrDefault();


            var Orders = from o in _context.OrderDetails
                      select o;

            Orders = Orders.Where(s => s.OrdersID == id);

            var OrderList = await Orders.ToListAsync();


            var AllProds = from p in _context.Products
                         select p;

           var AllProdList = _context.Products.Include(product => product.Category).ToList();


            var user = await _userManager.FindByIdAsync(Order.UserId.ToString());


            foreach (OrdersDetails order in OrderList)
            {

                var prod = AllProds.Where(s => s.ProductsID == order.ProductID).FirstOrDefault();

                ProdList.Add(prod);

            }

            vm.Products = ProdList;
            vm.Orders = Order;
            vm.OrdersDetails = Orders.ToList();
            vm.UserName = user.UserName;

            return View(vm);

        }




        // GET: Orders/Create

        public async Task<IActionResult> Create(string id)
        {



            var newOrder = new Orders();

            newOrder.UserId = id;
            newOrder.Status = "Pendiente";

            _context.Add(newOrder);
           
            await _context.SaveChangesAsync();



            var items = _context.ShoppingBasket.Where(i => i.UserID == id).ToList();

            foreach(ShoppingBasket item in items){

                var newOrderDetail = new OrdersDetails();

                newOrderDetail.OrdersID = newOrder.OrdersID;
                newOrderDetail.ProductID = item.ProductID;
                newOrderDetail.Amount = item.Amount;

                _context.Add(newOrderDetail);

            }

            await _context.SaveChangesAsync();

            var AdminUsers = _userManager.GetUsersInRoleAsync("Administrator").Result;

            var EmailList = new List<EmailAddress>();
                
            foreach(ApplicationUser user in AdminUsers)
            {
                EmailList.Add(new EmailAddress(user.Email));

            }


            await _emailSender.OrderCreatedEmailAsync(EmailList, newOrder.OrdersID.ToString());



            return RedirectToAction("Index"); 
        }

      


        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            _context.OrderDetails.Where(i => i.OrdersID == id).ToList().ForEach(p => _context.OrderDetails.Remove(p));

            var Order = await _context.Orders.SingleOrDefaultAsync(m => m.OrdersID == id);
           

            _context.Orders.Remove(Order);

            _context.SaveChanges();





            return RedirectToAction("Index"); 
        }



        // POST: Products/Delete/5
        [Authorize(Roles = "Administrator")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.SingleOrDefaultAsync(m => m.ProductsID == id);

            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delivered(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Order = await _context.Orders.SingleOrDefaultAsync(m => m.OrdersID == id);

            var user =await _userManager.FindByIdAsync(Order.UserId);

            var userEmail = _userManager.GetEmailAsync(user);

            Order.Status = "Entregado";

            _context.Update(Order);

            _context.SaveChanges();

            await _emailSender.SendDeliverEmailAsync(userEmail.Result.ToString(), Order.OrdersID.ToString());

            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using JDPesca.Models
@using JDPesca.Controllers

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JDPesca</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">


    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />

                            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    </environment>
</head>
<body>

<!--Shopping Cart BTN-->

@if (SignInManager.IsSignedIn(User)){
				<div class=" fixedBtn">
				<button id="btnShowModal" type="button" asp-controller="Home" asp-action="ModalPopUp" class=" btn btn-black btn-circle btn-lg"><i class="glyphicon glyphicon-shopping-cart"></i></button>
                 <span id="badgeText" class="badge badge-notify"></span>
                   </div>

               }
		<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">JDPesca</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

    @if ( User.IsInRole("Administrator")){

						<li><a asp-area="" asp-controller="Categories" asp-action="Index"><i class="fa fa-archive" aria-hidden="true"></i> Categorias</a></li>

                        <li><a asp-area="" asp-controller="Products" asp-action="Index"><i class="fa fa-list" aria-hidden="true"></i> Productos</a></li>   
                        						
						<li><a asp-area="" asp-controller="Contact" asp-action="ContactList"><i class="fa fa-users" aria-hidden="true"></i> Usuarios</a></li>   

                  }

              @if(SignInManager.IsSignedIn(User)){

                     <li><a asp-area="" asp-controller="Orders" asp-action="Index"><i class="fa fa-book" aria-hidden="true"></i> Ordenes</a></li> 
                        
                }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

                    
                    <br>
                     <br>
                     <br>
                     <br>
                     <br>
                    
        <footer class="footer">
            <p>&copy; 2018 - JDPesca</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)



    <!--Modal View-->
               <div class="modal fade" tabindex="-1" id="loginModal"  
                         data-keyboard="false" data-backdrop="static">  
                        <div class="modal-dialog modal-lg">  
                            <div class="modal-content">  
                                <div class="modal-header">  
                                    <button type="button" class="close" data-dismiss="modal">  
                                        ×  
                                    </button>  
								
                                    <h4 class="modal-title">Carrito</h4>  
                                </div>  
                                <div class="modal-body">  

					<p id="userid" type="hidden" style="display:none;" >@UserManager.GetUserId(User) </p>

								<i id="spinner" class="fa fa-spinner fa-spin" style="font-size:48px"></i>
					
						<div class="panel panel-primary">  
    <div class="panel-heading">  
        
								
    </div>   <!--en dof panel-heading -->
    <div class="panel-body">  
        <table class="table table-bordered" id="Table">  
            <tr>  
                <th>ProductID</th>  
                <th>Amount</th>  
				<th>Price</th>  
                <th>SubTotal</th> 
		        <th>Eliminar</th> 
            </tr>   <!--end of table-row -->
        </table>   <!--end of table -->
    </div> <!--end of Panel-body -->      
</div> <!--end of Panel -->  
						
                                </div>  
                                <div class="modal-footer">  
								     
								    <p  id="Total">Total = </p>
	                             <button style="float:left;" class='btn btn-danger' onClick='EmptyBasket(this.value)' value="@UserManager.GetUserId(User)">Vaciar Carrito <span class=' glyphicon glyphicon-trash'></span></button>
            
								<a class="btn btn-primary button button4" asp-controller="Orders" asp-action="Create" asp-route-id="@UserManager.GetUserId(User)">Procesar Orden</a>						
                                </div>  
                            </div>  
                        </div>  

<!--					Delete Msg-->
<div id="DeletedMsg" style="z-index: 10;" class="container alert alert-danger">
  <strong>Item Borrado!</strong> Se borro con exito del carrito!
</div>
                    </div>  
		    <!--Modal View-->
</body>
</html>

  <script type="text/javascript">  

	    var itemsArray = [];
		var total = 0;
        $(document).ready(function () {  

			loadBasket();

         $('#DeletedMsg').hide();
			
            $("#btnShowModal").click(function () {  

	$("#loginModal").modal('show');

    $('#spinner').show();
			
    $("#Table").find("tr:gt(0)").remove();

	//var url = "http://localhost:5000/api/shoppingbasket/getUserBasket?userID=" + $("#userid").text() ;

    var url = "/api/shoppingbasket/getUserBasket?userID=" + $("#userid").text() ;
    
            
 $.ajax({  
            type: "GET",  
            url: url,  
            contentType: "application/json; charset=utf-8",  
            dataType: "json",  
            success: function (data) {  
			$('#spinner').hide();
                //alert(JSON.stringify(data));                  
                $("#DIV").html('');   
                var DIV = ''; 

			total = 0;

			itemsArray = data;
			
                $.each(data, function (i, item) {  

			var itemcount = parseInt($("#badgeText").text());
			
			 $("#badgeText").text(i+1);

                var subtotal = item.price * item.amount;

                var borrarHref = 'api/ShoppingBasket/DeleteItem/'+item.shoppingBasketID;

                var shoppingBasketID = item.shoppingBasketID;

                    var rows = "<tr id="+shoppingBasketID+">" +   
                        "<td id='ProductName'>" + item.productName + "</td>" +  
                        "<td id='Amount'>" + item.amount + "</td>" + 
			"<td id='Price'>" + item.price + "</td>" +
			"<td id='Subtotal'>" + subtotal + "</td>" +
			"<td>" + " <button class='btn btn-danger' onClick='deleteItem(this.value)' value="+ shoppingBasketID +">Borrar <span class=' glyphicon glyphicon-trash'></span></button>" + "</td>" +
                        "</tr>";  
                    $('#Table').append(rows);  

			total = total + subtotal;            
			
                }); //End of foreach Loop  


			document.getElementById("Total").innerHTML = 'Total = $'+total;
			
                console.log(data);  
            }, //End of AJAX Success function  
  
            failure: function (data) {  
                //alert(data.responseText);  
            }, //End of AJAX failure function  
            error: function (data) {  
                //alert(data.responseText);  
            } //End of AJAX error function  
  
        });  

	
            });  
			
  
            $("#btnHideModal").click(function () {  
                $("#loginModal").modal('hide');  
            });  



}); 
                     

    </script>  

		<script>

			function loadBasket() {


            //var url = "http://localhost:5000/api/shoppingbasket/getUserBasket?userID=" + $("#userid").text() ;
                    var url = "/api/shoppingbasket/getUserBasket?userID=" + $("#userid").text() ;


 $.ajax({  
            type: "GET",  
            url: url,  
            contentType: "application/json; charset=utf-8",  
            dataType: "json",  
            success: function (data) {  
            $('#spinner').hide();
                //alert(JSON.stringify(data));                  
                $("#DIV").html('');   
                var DIV = ''; 

            total = 0;

            itemsArray = data;
            
                $.each(data, function (i, item) {  

            var itemcount = parseInt($("#badgeText").text());
            
             $("#badgeText").text(i+1);

               
                }); //End of foreach Loop  


            document.getElementById("Total").innerHTML = 'Total = $'+total;
            
                console.log(data);  
            }, //End of AJAX Success function  
  
            failure: function (data) {  
                //alert(data.responseText);  
            }, //End of AJAX failure function  
            error: function (data) {  
                //alert(data.responseText);  
            } //End of AJAX error function  
  
        }); 

			
			}
			
function deleteItem(item) {
			
    //alert(item);

	var url = '/api/shoppingbasket/DeleteItem';

   
    $.ajax({  
            type: "POST",  
            url: url,
			 data: item,
            contentType: "application/json; charset=utf-8",  
            dataType: "json",  
            success: function (data) {  

                //alert(JSON.stringify(data)); 
                $('#DeletedMsgs').stop();
			
                        var index = itemsArray.findIndex(x => x.shoppingBasketID == item);

                        total = total - itemsArray[index].price;

        			    document.getElementById("Total").innerHTML = 'Total = $'+total;
        			
           			    itemsArray.splice(index, 1);

			
            $("#"+item).fadeOut(500);

			var itemcount = parseInt($("#badgeText").text());
            
            $("#badgeText").text(itemcount-1);

			if($("#badgeText").text() == 0){
             $("#badgeText").fadeOut(1000);
			}
			
            $('#DeletedMsg').fadeIn(1000, function(){

            $('#DeletedMsg').fadeOut(3000);
        });

            }, //End of AJAX Success function  
  
            failure: function (data) {  
                alert(data.responseText);  
            }, //End of AJAX failure function  
            error: function (data) {  
                alert(data.responseText);  
            } //End of AJAX error function  
  
        });  
        		
  }


  function EmptyBasket(id) {

 
			
var url = '/api/shoppingbasket/EmptyBasket?userID=' + id;
            
 $.ajax({  
            type: "GET",  
            url: url,  
            contentType: "application/json; charset=utf-8",  
            dataType: "json",  
            success: function (data) {  


            }, //End of AJAX Success function  
  
            failure: function (data) {  
                alert(data.responseText);  
            }, //End of AJAX failure function  
            error: function (data) {  
                
			 $("#badgeText").text('0');
             $("#badgeText").fadeOut(1000);
			 $("#loginModal").modal('hide');

			} //End of AJAX error function  
  
        }); 

            
            }
</script>


		